---

spring:
  application:
    name: app
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always
  profiles:
    default: development

# src/main/resources/certs
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

sentry:
  send-default-pii: true
  sentry.environment: prod