# BEGIN
spring:
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true

sentry:
  dsn: ""
  enabled: false

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

